title: Curriculum
author: Vinícius Ferreira
email: antifadev.web@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Curriculum e Portfolio de Vinícius Ferreira

# social links
twitter_username: @ViniciusFerreir9
github_username:  @Vinicius-BFerreira

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
